name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker-compose up --build -d

  test:

    needs: build

    steps:
      - name: Test for python code
        run: |
          docker-compose exec web manage.py test
          docker-compose exec web flake8
